[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[rpc_endpoints]
sepolia = "https://rpc.ankr.com/eth_sepolia"
fuji = "https://avalanche-fuji-c-chain-rpc.publicnode.com"
 
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
fuji = { key = "${AVALANCHE_API_KEY}", chain = 43113, url = "https://api.avax-test.network/ext/bc/C/rpc" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
